fail_fast: true
repos:
- repo: local
  hooks:
    - id: pre-commit
      name: Fmt
      entry: bash -c 'just fmt'
      language: system
      verbose: true
      always_run: true
      pass_filenames: false
      types: [file]
      stages:
        - pre-commit
- repo: local
  hooks:
    - id: pre-push
      name: Lint & Test
      entry: bash -c 'just pre-push'
      pass_filenames: false
      verbose: true
      language: system
      always_run: true
      types: [file]
      stages:
        - pre-push
default_stages:
  - pre-push
