name: cli_command_with_tf

inputs:
  cli_command:
    description: 'CLI command to run with args atlas-init {cli_command}'
    required: true
  atlas_init_repo_path:
    description: 'Path to the atlas-init directory'
    required: true
  profile_name:
    description: 'Profile name to use for the atlas init CLI command'
    default: default
  cleanup:
    description: 'Cleanup the resources after the command is run'
    default: "true"

runs:
  using: composite
  steps:
  - name: atlas-init-install
    run: |
        cd ${{ inputs.atlas_init_repo_path }}
        mkdir -p profiles/${{ inputs.profile_name }}
        echo "ATLAS_INIT_PROFILES_PATH=$(pwd)/profiles" >> $GITHUB_ENV
        echo "ATLAS_INIT_PROFILE=${{ inputs.profile_name }}" >> $GITHUB_ENV
        ./atlasci_local_install.sh
  - name: atlas-init-init
    run: source atlas-init/.venv/bin/activate && cd tf && atlas-init init
  - name: atlas-init-apply
    run: source atlas-init/.venv/bin/activate && cd tf && atlas-init apply -auto-approve
  - name: atlas-init-command
    run: source atlas-init/.venv/bin/activate && cd tf && atlas-init ${{ inputs.cli_command }}
  - name: atlas-init-destroy
    run: source atlas-init/.venv/bin/activate && cd tf && atlas-init destroy -auto-approve
    if: ${{ inputs.cleanup == 'true' && always() }}



