name: cli_command_with_tf

inputs:
  step_name:
    description: 'Name of the step'
    default: 'command'
  cli_command:
    description: 'CLI command to run with args atlas-init {cli_command}'
    required: true
  atlas_init_repo_path:
    description: 'Path to the atlas-init directory'
    required: true
  cwd:
    description: 'Current working directory'
    required: true
  profile_name:
    description: 'Profile name to use for the atlas init CLI command'
    default: default
  cleanup:
    description: 'Cleanup the resources after the command is run'
    default: "true"
  dry_run_first:
    description: 'Run with dry-run before full run'
    default: "false"

runs:
  using: composite
  steps:
  - name: atlas-init-install
    shell: bash
    run: |
        cd ${{ inputs.atlas_init_repo_path }}
        mkdir -p profiles/${{ inputs.profile_name }}
        echo "ATLAS_INIT_PROFILES_PATH=$(pwd)/profiles" >> $GITHUB_ENV
        echo "ATLAS_INIT_PROFILE=${{ inputs.profile_name }}" >> $GITHUB_ENV
        ./atlasci_local_install.sh
  - name: atlas-init-init
    shell: bash
    run: source ${{ inputs.atlas_init_repo_path }}/.venv/bin/activate && cd ${{ inputs.cwd }} && atlas-init init
  - name: atlas-init-apply
    shell: bash
    run: source ${{ inputs.atlas_init_repo_path }}/.venv/bin/activate && cd ${{ inputs.cwd }} && atlas-init apply -auto-approve
  - name: atlas-init-dry-run-${{ inputs.step_name }}
    shell: bash
    run: source ${{ inputs.atlas_init_repo_path }}/.venv/bin/activate && cd ${{ inputs.cwd }} && atlas-init --dry-run ${{ inputs.cli_command }}
    if : ${{ inputs.dry_run_first == 'true' }}
  - name: atlas-init-${{ inputs.step_name }}
    shell: bash
    run: source ${{ inputs.atlas_init_repo_path }}/.venv/bin/activate && cd ${{ inputs.cwd }} && atlas-init ${{ inputs.cli_command }}
  - name: atlas-init-destroy
    shell: bash
    run: source ${{ inputs.atlas_init_repo_path }}/.venv/bin/activate && cd ${{ inputs.cwd }} && atlas-init destroy -auto-approve
    if: ${{ inputs.cleanup == 'true' && always() }}
