name: setup_steps
description: 'Setup steps for the workflow to use `atlas-init`'

inputs:
  tf_version:
    description: 'Set to also install Terraform'
    default: ''
  extra_pypi_packages:
    description: 'Extra pip packages to install'
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff
      with:
        just-version: '1.40.0'
    - uses: yezz123/setup-uv@v4
      with:
        uv-version: "0.6.14"
    - name: dependency install
      run: uv pip install -U hatch==1.11.0 ${{ inputs.extra_pypi_packages }} --system
      shell: bash
    - uses: hashicorp/setup-terraform@v3
      name: configure terraform specific version
      if: ${{ inputs.tf_version != '' && inputs.tf_version != 'default' }}
      with:
        terraform_version: ${{ inputs.tf_version }}
    - uses: hashicorp/setup-terraform@v3
      name: configure terraform default version
      if: ${{ inputs.tf_version == 'default' }}
      with:
        terraform_version: "1.10.2"
