schema:
  description: Creates Search Nodes for the specified cluster.
  attributes:
    - string:
      description: Label that identifies the cluster to create Search Nodes for.
      name: cluster_name
      computedoptionalrequired: required
    - string:
      description: |-
        Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.

        **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.
      name: project_id
      computedoptionalrequired: required
    - string:
      description: Unique 24-hexadecimal digit string that identifies the search deployment.
      name: id
      computedoptionalrequired: computed
    - listnested:
        nestedobject:
          attributes:
            - string:
              description: Hardware specification for the Search Node instance sizes.
              name: instance_size
              computedoptionalrequired: required
            - int64:
              description: Number of Search Nodes in the cluster.
              name: node_count
              computedoptionalrequired: required
      description: List of settings that configure the Search Nodes for your cluster.
      name: specs
      computedoptionalrequired: required
    - string:
      description: Human-readable label that indicates the current operating condition of this search deployment.
      name: state_name
      computedoptionalrequired: computed
    - timeouts:
        configurabletimeouts:
          - 0
          - 1
          - 3
      name: timeouts
      computedoptionalrequired: ""
name: search_deployment

