openapi: 3.0.1
info:
  description: minimal spec
paths:
  /api/atlas/v2/orgs/{orgId}/resourcePolicies/{resourcePolicyId}:
    delete:
      description: Delete one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: deleteAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              x-xgen-version: '2024-08-05'
          description: This endpoint does not return a response body.
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Delete one Atlas Resource Policy
      tags:
      - Resource Policies
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/deleteAtlasResourcePolicy
    get:
      description: Return one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: getAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-IPA-exception:
                xgen-IPA-104-get-method-returns-response-suffixed-object: API predates IPA validation
              x-xgen-version: '2024-08-05'
          description: OK
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return one Atlas Resource Policy
      tags:
      - Resource Policies
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/getAtlasResourcePolicy
    patch:
      description: Update one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: updateAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      requestBody:
        content:
          application/vnd.atlas.2024-08-05+json:
            schema:
              $ref: '#/components/schemas/ApiAtlasResourcePolicyEditView'
            x-xgen-version: '2024-08-05'
        description: Atlas Resource Policy to update.
        required: true
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-version: '2024-08-05'
          description: Ok
        '400':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasInvalidResourcePolicyCreateErrorView'
              x-xgen-version: '2024-08-05'
          description: Bad request.
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Update one Atlas Resource Policy
      tags:
      - Resource Policies
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/updateAtlasResourcePolicy
  /api/atlas/v2/orgs/{orgId}/resourcePolicies:
    get:
      description: Return all Atlas Resource Policies for the org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: getAtlasResourcePolicies
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                items:
                  $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
                type: array
                x-xgen-IPA-exception:
                  xgen-IPA-124-array-max-items: Schema predates IPA validation
              x-xgen-IPA-exception:
                xgen-IPA-110-collections-response-define-links-array: Content predates IPA validation
                xgen-IPA-110-collections-response-define-results-array: Content predates IPA validation
                xgen-IPA-110-collections-use-paginated-prefix: Content predates IPA validation
              x-xgen-version: '2024-08-05'
          description: OK
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Return all Atlas Resource Policies
      tags:
      - Resource Policies
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/getAtlasResourcePolicies
    post:
      description: Create one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: createAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      requestBody:
        content:
          application/vnd.atlas.2024-08-05+json:
            schema:
              $ref: '#/components/schemas/ApiAtlasResourcePolicyCreateView'
            x-xgen-version: '2024-08-05'
        description: Atlas Resource Policy to create.
        required: true
      responses:
        '201':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-version: '2024-08-05'
          description: Created
        '400':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasInvalidResourcePolicyCreateErrorView'
              x-xgen-version: '2024-08-05'
          description: Bad request.
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: Create one Atlas Resource Policy
      tags:
      - Resource Policies
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/createAtlasResourcePolicy
components:
  schemas:
    ApiAtlasResourcePolicyView:
      properties:
        createdByUser:
          $ref: '#/components/schemas/ApiAtlasUserMetadataView'
          name: createdByUser
        createdDate:
          description: Date and time in UTC when the atlas resource policy was created.
          format: date-time
          readOnly: true
          type: string
          name: createdDate
        description:
          description: Description of the atlas resource policy.
          readOnly: true
          type: string
          name: description
        id:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
          name: id
        lastUpdatedByUser:
          $ref: '#/components/schemas/ApiAtlasUserMetadataView'
          name: lastUpdatedByUser
        lastUpdatedDate:
          description: Date and time in UTC when the atlas resource policy was last updated.
          format: date-time
          readOnly: true
          type: string
          name: lastUpdatedDate
        name:
          description: Human-readable label that describes the atlas resource policy.
          readOnly: true
          type: string
          name: name
        orgId:
          description: Unique 24-hexadecimal character string that identifies the organization the atlas resource policy belongs to.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
          name: orgId
        policies:
          description: List of policies that make up the atlas resource policy.
          items:
            $ref: '#/components/schemas/ApiAtlasPolicyView'
          readOnly: true
          type: array
          name: policies
        version:
          description: A string that identifies the version of the atlas resource policy.
          example: v1
          readOnly: true
          type: string
          name: version
      type: object
    ApiAtlasResourcePolicyCreateView:
      properties:
        description:
          description: Description of the atlas resource policy.
          type: string
          name: description
        name:
          description: Human-readable label that describes the atlas resource policy.
          type: string
          name: name
        policies:
          description: List of policies that make up the atlas resource policy.
          items:
            $ref: '#/components/schemas/ApiAtlasPolicyCreateView'
          type: array
          name: policies
      required:
      - name
      - policies
      type: object
    ApiAtlasUserMetadataView:
      description: The user that last updated the atlas resource policy.
      properties:
        id:
          description: Unique 24-hexadecimal character string that identifies a user.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
          name: id
        name:
          description: Human-readable label that describes a user.
          readOnly: true
          type: string
          name: name
      readOnly: true
      type: object
    ApiAtlasPolicyView:
      properties:
        body:
          description: A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
          example: "  forbid (\n    principal,\n    action == cloud::Action::\"cluster.createEdit\",\n    resource\n  ) when {\n   context.cluster.regions.contains(cloud::region::\"aws:us-east-1\")\n  };\n"
          readOnly: true
          type: string
          name: body
        id:
          description: Unique 24-hexadecimal character string that identifies the policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
          name: id
      type: object
    ApiAtlasPolicyCreateView:
      properties:
        body:
          description: A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
          example: "  forbid (\n    principal,\n    action == cloud::Action::\"cluster.createEdit\",\n    resource\n  ) when {\n   context.cluster.regions.contains(cloud::region::\"aws:us-east-1\")\n  };\n"
          type: string
          name: body
      required:
      - body
      type: object
  parameters: {}
tags: []
