openapi: 3.0.1
info:
  description: minimal spec
paths:
  /api/atlas/v2/groups/{groupId}/pushBasedLogExport:
    delete:
      description: Disables the push-based log export feature by resetting the project level settings to its default configuration.
      operationId: deletePushBasedLogConfiguration
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          content:
            application/vnd.atlas.2023-01-01+json:
              x-xgen-version: '2023-01-01'
          description: OK
      summary: Disable the push-based log export feature for a project
      tags:
      - Push-Based Log Export
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Push-Based-Log-Export/operation/deletePushBasedLogConfiguration
    get:
      description: Fetches the current project level settings for the push-based log export feature.
      operationId: getPushBasedLogConfiguration
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          content:
            application/vnd.atlas.2023-01-01+json:
              schema:
                $ref: '#/components/schemas/PushBasedLogExportProject'
              x-xgen-IPA-exception:
                xgen-IPA-110-collections-response-define-results-array: Singleton method, mistakenly identified as a List method.
                xgen-IPA-110-collections-use-paginated-prefix: Singleton method, mistakenly identified as a List method.
              x-xgen-version: '2023-01-01'
          description: OK
      summary: Get the push-based log export configuration for a project
      tags:
      - Push-Based Log Export
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Push-Based-Log-Export/operation/getPushBasedLogConfiguration
    patch:
      description: Updates the project level settings for the push-based log export feature.
      operationId: updatePushBasedLogConfiguration
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/pretty'
      requestBody:
        content:
          application/vnd.atlas.2023-01-01+json:
            schema:
              $ref: '#/components/schemas/PushBasedLogExportProject'
            x-xgen-version: '2023-01-01'
        description: The project configuration details. The S3 bucket name, IAM role ID, and prefix path fields are the only fields that may be specified. Fields left unspecified will not be modified.
        required: true
      responses:
        '200':
          content:
            application/vnd.atlas.2023-01-01+json:
              x-xgen-version: '2023-01-01'
          description: OK
      summary: Update the push-based log export feature for a project
      tags:
      - Push-Based Log Export
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Push-Based-Log-Export/operation/updatePushBasedLogConfiguration
    post:
      description: Configures the project level settings for the push-based log export feature.
      operationId: createPushBasedLogConfiguration
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/groupId'
      - $ref: '#/components/parameters/pretty'
      requestBody:
        content:
          application/vnd.atlas.2023-01-01+json:
            schema:
              $ref: '#/components/schemas/CreatePushBasedLogExportProjectRequest'
            x-xgen-version: '2023-01-01'
        description: The project configuration details. The S3 bucket name, IAM role ID, and prefix path fields are required.
        required: true
      responses:
        '200':
          content:
            application/vnd.atlas.2023-01-01+json:
              x-xgen-version: '2023-01-01'
          description: OK
      summary: Enable the push-based log export feature for a project
      tags:
      - Push-Based Log Export
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Push-Based-Log-Export/operation/createPushBasedLogConfiguration
components:
  schemas:
    CreatePushBasedLogExportProjectRequest:
      properties:
        bucketName:
          description: The name of the bucket to which the agent will send the logs to.
          type: string
          name: bucketName
        iamRoleId:
          description: ID of the AWS IAM role that will be used to write to the S3 bucket.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          type: string
          name: iamRoleId
        links:
          description: List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
          externalDocs:
            description: Web Linking Specification (RFC 5988)
            url: https://datatracker.ietf.org/doc/html/rfc5988
          items:
            $ref: '#/components/schemas/Link'
          readOnly: true
          type: array
          name: links
        prefixPath:
          description: S3 directory in which vector will write to in order to store the logs. An empty string denotes the root directory.
          type: string
          name: prefixPath
      required:
      - bucketName
      - iamRoleId
      - prefixPath
      type: object
    Link:
      properties:
        href:
          description: Uniform Resource Locator (URL) that points another API resource to which this response has some relationship. This URL often begins with `https://cloud.mongodb.com/api/atlas`.
          example: https://cloud.mongodb.com/api/atlas
          type: string
          name: href
        rel:
          description: Uniform Resource Locator (URL) that defines the semantic relationship between this resource and another API resource. This URL often begins with `https://cloud.mongodb.com/api/atlas`.
          example: self
          type: string
          name: rel
      type: object
    PushBasedLogExportProject:
      properties:
        bucketName:
          description: The name of the bucket to which the agent will send the logs to.
          type: string
          name: bucketName
        createDate:
          description: Date and time that this feature was enabled on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
          format: date-time
          readOnly: true
          type: string
          name: createDate
        iamRoleId:
          description: ID of the AWS IAM role that will be used to write to the S3 bucket.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          type: string
          name: iamRoleId
        links:
          description: List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
          externalDocs:
            description: Web Linking Specification (RFC 5988)
            url: https://datatracker.ietf.org/doc/html/rfc5988
          items:
            $ref: '#/components/schemas/Link'
          readOnly: true
          type: array
          name: links
        prefixPath:
          description: S3 directory in which vector will write to in order to store the logs. An empty string denotes the root directory.
          type: string
          name: prefixPath
        state:
          description: Describes whether or not the feature is enabled and what status it is in.
          enum:
          - UNCONFIGURED
          - INITIATING
          - BUCKET_VERIFIED
          - BUCKET_VERIFICATION_FAILED
          - ASSUME_ROLE_FAILED
          - ACTIVE
          readOnly: true
          type: string
          name: state
      type: object
  parameters:
    envelope:
      description: Flag that indicates whether Application wraps the response in an `envelope` JSON object. Some API clients cannot access the HTTP response headers or status code. To remediate this, set envelope=true in the query. Endpoints that return a list of results use the results object as an envelope. Application adds the status parameter to the response body.
      in: query
      name: envelope
      schema:
        default: false
        type: boolean
    groupId:
      description: 'Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.


        **NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.'
      in: path
      name: groupId
      required: true
      schema:
        example: 32b6e34b3d91647abb20e7b8
        pattern: ^([a-f0-9]{24})$
        type: string
      x-xgen-IPA-exception:
        xgen-IPA-117-description-should-not-use-inline-links: Parameters don't support externalDocs
    pretty:
      description: Flag that indicates whether the response body should be in the prettyprint format.
      in: query
      name: pretty
      schema:
        default: false
        externalDocs:
          description: Prettyprint
          url: https://en.wikipedia.org/wiki/Prettyprint
        type: boolean
tags: []
