openapi: 3.0.1
info:
  description: minimal spec
  version: '2.0'
  title: MongoDB Atlas Administration API
paths:
  /api/atlas/v2/orgs/{orgId}/resourcePolicies/{resourcePolicyId}:
    delete:
      description: Delete one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: deleteAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              x-xgen-version: '2024-08-05'
          description: This endpoint does not return a response body.
      summary: Delete one Atlas Resource Policy
      tags:
      - Resource Policies
      x-codeSamples:
      - label: curl
        lang: cURL
        source: "curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\\n  --digest \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X DELETE \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/resourcePolicies/{resourcePolicyId}\""
      - label: Atlas CLI
        lang: cURL
        source: atlas api deleteAtlasResourcePolicy --help
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/deleteAtlasResourcePolicy
    get:
      description: Return one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: getAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-IPA-exception:
                xgen-IPA-104-get-method-returns-response-suffixed-object: API predates IPA validation
              x-xgen-version: '2024-08-05'
          description: OK
      summary: Return one Atlas Resource Policy
      tags:
      - Resource Policies
      x-codeSamples:
      - label: curl
        lang: cURL
        source: "curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\\n  --digest \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/resourcePolicies/{resourcePolicyId}?pretty=true\""
      - label: Atlas CLI
        lang: cURL
        source: atlas api getAtlasResourcePolicy --help
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/getAtlasResourcePolicy
    patch:
      description: Update one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: updateAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      - description: Unique 24-hexadecimal digit string that identifies an atlas resource policy.
        in: path
        name: resourcePolicyId
        required: true
        schema:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      requestBody:
        content:
          application/vnd.atlas.2024-08-05+json:
            schema:
              $ref: '#/components/schemas/ApiAtlasResourcePolicyEditView'
            x-xgen-version: '2024-08-05'
        description: Atlas Resource Policy to update.
        required: true
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-version: '2024-08-05'
          description: Ok
      summary: Update one Atlas Resource Policy
      tags:
      - Resource Policies
      x-codeSamples:
      - label: curl
        lang: cURL
        source: "curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\\n  --digest \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/vnd.atlas.2025-03-12+json\" \\\n  -X PATCH \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/resourcePolicies/{resourcePolicyId}\"\n  -d { <Payload> }"
      - label: Atlas CLI
        lang: cURL
        source: atlas api updateAtlasResourcePolicy --help
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/updateAtlasResourcePolicy
  /api/atlas/v2/orgs/{orgId}/resourcePolicies:
    get:
      description: Return all Atlas Resource Policies for the org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: getAtlasResourcePolicies
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      responses:
        '200':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                items:
                  $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
                type: array
                x-xgen-IPA-exception:
                  xgen-IPA-124-array-max-items: Schema predates IPA validation
              x-xgen-IPA-exception:
                xgen-IPA-110-collections-response-define-links-array: Content predates IPA validation
                xgen-IPA-110-collections-response-define-results-array: Content predates IPA validation
                xgen-IPA-110-collections-use-paginated-prefix: Content predates IPA validation
              x-xgen-version: '2024-08-05'
          description: OK
      summary: Return all Atlas Resource Policies
      tags:
      - Resource Policies
      x-codeSamples:
      - label: curl
        lang: cURL
        source: "curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\\n  --digest \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  -X GET \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/resourcePolicies?pretty=true\""
      - label: Atlas CLI
        lang: cURL
        source: atlas api getAtlasResourcePolicies --help
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/getAtlasResourcePolicies
    post:
      description: Create one Atlas Resource Policy for an org.
      externalDocs:
        description: Atlas Resource Policies
        url: https://dochub.mongodb.org/core/atlas-resource-policies
      operationId: createAtlasResourcePolicy
      parameters:
      - $ref: '#/components/parameters/envelope'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/orgId'
      requestBody:
        content:
          application/vnd.atlas.2024-08-05+json:
            schema:
              $ref: '#/components/schemas/ApiAtlasResourcePolicyCreateView'
            x-xgen-version: '2024-08-05'
        description: Atlas Resource Policy to create.
        required: true
      responses:
        '201':
          content:
            application/vnd.atlas.2024-08-05+json:
              schema:
                $ref: '#/components/schemas/ApiAtlasResourcePolicyView'
              x-xgen-version: '2024-08-05'
          description: Created
      summary: Create one Atlas Resource Policy
      tags:
      - Resource Policies
      x-codeSamples:
      - label: curl
        lang: cURL
        source: "curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\\n  --digest \\\n  --header \"Accept: application/vnd.atlas.2025-03-12+json\" \\\n  --header \"Content-Type: application/vnd.atlas.2025-03-12+json\" \\\n  -X POST \"https://cloud.mongodb.com/api/atlas/v2/orgs/{orgId}/resourcePolicies\"\n  -d { <Payload> }"
      - label: Atlas CLI
        lang: cURL
        source: atlas api createAtlasResourcePolicy --help
      x-xgen-docs-url: https://mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Resource-Policies/operation/createAtlasResourcePolicy
components:
  schemas:
    ApiAtlasPolicyCreateView:
      properties:
        body:
          description: A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
          example: "  forbid (\n    principal,\n    action == cloud::Action::\"cluster.createEdit\",\n    resource\n  ) when {\n   context.cluster.regions.contains(cloud::region::\"aws:us-east-1\")\n  };\n"
          type: string
      required:
      - body
      type: object
    ApiAtlasPolicyView:
      properties:
        body:
          description: A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
          example: "  forbid (\n    principal,\n    action == cloud::Action::\"cluster.createEdit\",\n    resource\n  ) when {\n   context.cluster.regions.contains(cloud::region::\"aws:us-east-1\")\n  };\n"
          readOnly: true
          type: string
        id:
          description: Unique 24-hexadecimal character string that identifies the policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
      type: object
    ApiAtlasResourcePolicyCreateView:
      properties:
        description:
          description: Description of the atlas resource policy.
          type: string
        name:
          description: Human-readable label that describes the atlas resource policy.
          type: string
        policies:
          description: List of policies that make up the atlas resource policy.
          items:
            $ref: '#/components/schemas/ApiAtlasPolicyCreateView'
          type: array
      required:
      - name
      - policies
      type: object
    ApiAtlasResourcePolicyEditView:
      properties:
        description:
          description: Description of the atlas resource policy.
          type: string
        name:
          description: Human-readable label that describes the atlas resource policy.
          type: string
        policies:
          description: List of policies that make up the atlas resource policy.
          items:
            $ref: '#/components/schemas/ApiAtlasPolicyCreateView'
          type: array
      type: object
    ApiAtlasResourcePolicyView:
      properties:
        createdByUser:
          $ref: '#/components/schemas/ApiAtlasUserMetadataView'
        createdDate:
          description: Date and time in UTC when the atlas resource policy was created.
          format: date-time
          readOnly: true
          type: string
        description:
          description: Description of the atlas resource policy.
          readOnly: true
          type: string
        id:
          description: Unique 24-hexadecimal character string that identifies the atlas resource policy.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
        lastUpdatedByUser:
          $ref: '#/components/schemas/ApiAtlasUserMetadataView'
        lastUpdatedDate:
          description: Date and time in UTC when the atlas resource policy was last updated.
          format: date-time
          readOnly: true
          type: string
        name:
          description: Human-readable label that describes the atlas resource policy.
          readOnly: true
          type: string
        orgId:
          description: Unique 24-hexadecimal character string that identifies the organization the atlas resource policy belongs to.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
        policies:
          description: List of policies that make up the atlas resource policy.
          items:
            $ref: '#/components/schemas/ApiAtlasPolicyView'
          readOnly: true
          type: array
        version:
          description: A string that identifies the version of the atlas resource policy.
          example: v1
          readOnly: true
          type: string
      type: object
    ApiAtlasUserMetadataView:
      description: The user that last updated the atlas resource policy.
      properties:
        id:
          description: Unique 24-hexadecimal character string that identifies a user.
          example: 32b6e34b3d91647abb20e7b8
          pattern: ^([a-f0-9]{24})$
          readOnly: true
          type: string
        name:
          description: Human-readable label that describes a user.
          readOnly: true
          type: string
      readOnly: true
      type: object
  parameters:
    envelope:
      description: Flag that indicates whether Application wraps the response in an `envelope` JSON object. Some API clients cannot access the HTTP response headers or status code. To remediate this, set envelope=true in the query. Endpoints that return a list of results use the results object as an envelope. Application adds the status parameter to the response body.
      in: query
      name: envelope
      schema:
        default: false
        type: boolean
    orgId:
      description: Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.
      in: path
      name: orgId
      required: true
      schema:
        example: 4888442a3354817a7320eb61
        pattern: ^([a-f0-9]{24})$
        type: string
      x-xgen-IPA-exception:
        xgen-IPA-117-description-should-not-use-inline-links: Parameters don't support externalDocs
    pretty:
      description: Flag that indicates whether the response body should be in the prettyprint format.
      in: query
      name: pretty
      schema:
        default: false
        externalDocs:
          description: Prettyprint
          url: https://en.wikipedia.org/wiki/Prettyprint
        type: boolean
tags: []
