name: 'CI CFN ACC'

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder name'
        required: true
        default: 'trigger'

concurrency:
    group: '${{ github.workflow }}'
    cancel-in-progress: false

env:
  FORCE_COLOR: "yes"
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_BASE_URL: https://cloud-dev.mongodb.com/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  TF_INPUT: "false"
  NON_INTERACTIVE: "true"
  FOLDER_PATH: "cfn/cfn-resources/${{ inputs.folder_name }}"
  TF_VAR_use_project_myip: "false"
  ATLAS_INIT_CFN_PROFILE: profile-${{ github.run_id }}
  ATLAS_INIT_CFN_REGION: eu-west-1
  ATLAS_INIT_CFN_USE_KMS_KEY: "false"
  ATLAS_INIT_PROJECT_NAME: gh-ci-${{ github.run_id }}
  
jobs:
  cli_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: atlas-init-checkout
        with:
          path: atlas-init
      - uses: actions/checkout@v4
        name: terraform-provider-mongodbatlas-checkout
        with:
          repository: mongodb/mongodbatlas-cloudformation-resources
          path: cfn
          ref: 28a7488aeae8e0212c1ee36483f0fd239ffa9371
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
        with:
            uv-version: "0.1.12"
      - name: hatch-install
        run: |
          uv pip install -U hatch==1.11.0 zero-3rdparty==0.0.30 --system
      - name: atlas-init-install
        run: |
          cd atlas-init
          mkdir -p profiles/default
          echo "ATLAS_INIT_PROFILES_PATH=$(pwd)/profiles" >> $GITHUB_ENV
          ./atlasci_local_install.sh
      - uses: hashicorp/setup-terraform@v3
        name: configure terraform
        with:
          terraform_version: "1.10.2"
      - name: atlas-init-init
        run: source atlas-init/.venv/bin/activate && cd cfn && atlas-init init
      - name: atlas-init-apply
        run: source atlas-init/.venv/bin/activate && cd ${{ env.FOLDER_PATH}} && atlas-init apply -auto-approve
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'cfn/cfn-resources/go.mod'
      - name: atlas-init-contract-test-dry-run
        run: source atlas-init/.venv/bin/activate && cd ${{ env.FOLDER_PATH}} && atlas_init --dry-run cfn contract-test
      - name: atlas-init-contract-test-dry-run
        run: source atlas-init/.venv/bin/activate && cd ${{ env.FOLDER_PATH}} && atlas_init cfn contract-test
      - name: atlas-init-destroy
        run: source atlas-init/.venv/bin/activate && cd ${{ env.FOLDER_PATH}} && atlas-init destroy -auto-approve
        if: always()
