name: 'CI CFN ACC'

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS region'
        required: true
        default: 'eu-west-1'
      folder_name:
        description: 'Folder name'
        required: true
        default: 'trigger'

concurrency:
    group: '${{ github.workflow }}'
    cancel-in-progress: false

env:
  COLUMNS: 140
  FORCE_COLOR: "yes"
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_BASE_URL: https://cloud-dev.mongodb.com/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ inputs.AWS_REGION }}
  TF_INPUT: "false"
  NON_INTERACTIVE: "true"
  FOLDER_PATH: "cfn/cfn-resources/${{ inputs.folder_name }}"
  TF_VAR_use_project_myip: "false"
  # should always mange its own CFN secret
  ATLAS_INIT_CFN_PROFILE: profile-${{ github.run_id }}
  ATLAS_INIT_CFN_REGION: ${{ inputs.AWS_REGION }}
  ATLAS_INIT_CFN_USE_KMS_KEY: "false"
  ATLAS_INIT_PROFILE: ${{ format('profile-{0}',github.run_id) }}
  ATLAS_INIT_PROJECT_NAME: ${{ format('gh-ci-{0}', github.run_id) }}
  
jobs:
  cli_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: atlas-init-checkout
        with:
          path: atlas-init
      - name: setup_steps
        uses: "./atlas-init/.github/templates/setup_steps"
        with:
          tf_version: "default"
          extra_pypi_packages: "cloudformation-cli cloudformation-cli-go-plugin setuptools"
      - uses: actions/checkout@v4
        name: terraform-provider-mongodbatlas-checkout
        with:
          repository: mongodb/mongodbatlas-cloudformation-resources
          path: cfn
          ref: 28a7488aeae8e0212c1ee36483f0fd239ffa9371
      - uses: aws-actions/setup-sam@2360ef6d90015369947b45b496193ab9976a9b04
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
            go-version-file: 'cfn/cfn-resources/go.mod'
      - name: cli_command_with_tf
        uses: "./atlas-init/.github/templates/cli_command_with_tf"
        with:
          cli_command: "cfn contract-test"
          atlas_init_repo_path: "atlas-init"
          cwd: ${{ env.FOLDER_PATH}}
          profile_name: ${{ env.ATLAS_INIT_PROFILE }}
          dry_run_first: "true"
