name: 'CI CFN ACC Manual'

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      folder_name:
        description: 'Folder name'
        required: true
        default: 'trigger'
      profile_s3_bucket:
        description: 'S3 bucket for profiles'
        required: true
      atlas_init_profile:
        description: 'Atlas init profile, useful when using profile_s3_bucket, otherwise creating a new profile'
        required: true
        

concurrency:
    group: '${{ github.workflow }}'
    cancel-in-progress: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ inputs.AWS_REGION }}
  FOLDER_PATH: "cfn/cfn-resources/${{ inputs.folder_name }}"
  ATLAS_INIT_PROFILE: ${{ inputs.atlas_init_profile }}
  ATLAS_INIT_S3_PROFILE_BUCKET: ${{ inputs.profile_s3_bucket }}
  FORCE_COLOR: "yes"
  COLUMNS: 140
  TF_INPUT: "false"
  NON_INTERACTIVE: "true"
  
jobs:
  cli_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: atlas-init-checkout
        with:
          path: atlas-init
      - uses: actions/checkout@v4
        name: cfn-checkout
        with:
          repository: mongodb/mongodbatlas-cloudformation-resources
          path: cfn
          ref: 28a7488aeae8e0212c1ee36483f0fd239ffa9371
      - name: setup_steps
        uses: "./atlas-init/.github/templates/setup_steps"
        with:
          tf_version: "default"
          extra_pypi_packages: "cloudformation-cli cloudformation-cli-go-plugin setuptools"
      - uses: aws-actions/setup-sam@2360ef6d90015369947b45b496193ab9976a9b04
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
            go-version-file: 'cfn/cfn-resources/go.mod'
      - name: cli_command_with_tf
        uses: "./atlas-init/.github/templates/cli_command_with_tf"
        with:
          cli_command: "cfn contract-test"
          atlas_init_repo_path: "atlas-init"
          cwd: ${{ env.FOLDER_PATH}}
          profile_name: ${{ env.ATLAS_INIT_PROFILE }}
          dry_run_first: "true"
          cleanup: "false"
