name: 'CI TF ACC'

on:
  push:
    branches: "*"

concurrency:
    group: '${{ github.workflow }}'
    cancel-in-progress: false

env:
  FORCE_COLOR: "yes"
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  ATLAS_INIT_PROJECT_NAME: github-ci-tf-federated
  MONGODB_ATLAS_BASE_URL: https://cloud-dev.mongodb.com/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  TF_INPUT: "false"
  ATLAS_INIT_TEST_SUITES: federated
  TF_VAR_federated_settings_id: ${{ secrets.TF_VAR_federated_settings_id }}
  NON_INTERACTIVE: "true"
  
jobs:
  cli_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: atlas-init-checkout
        with:
          path: atlas-init
      - name: setup_steps
        uses: "./atlas-init/.github/templates/setup_steps"
        with:
          tf_version: "default"
      - uses: actions/checkout@v4
        name: terraform-provider-mongodbatlas-checkout
        with:
          repository: mongodb/terraform-provider-mongodbatlas
          path: tf
          ref: df44242152a96883f0535d2dc6b62ecae76d9e4e
      - name: atlas-init-install
        run: |
          cd atlas-init
          mkdir -p profiles/default
          echo "ATLAS_INIT_PROFILES_PATH=$(pwd)/profiles" >> $GITHUB_ENV
          ./atlasci_local_install.sh
      - name: atlas-init-init
        run: source atlas-init/.venv/bin/activate && cd tf && atlas-init init
      - name: atlas-init-apply
        run: source atlas-init/.venv/bin/activate && cd tf && atlas-init apply -auto-approve
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'tf/go.mod'
      - name: atlas-init-test-go
        run: source atlas-init/.venv/bin/activate && cd tf && atlas-init go-test
      - name: atlas-init-destroy
        run: source atlas-init/.venv/bin/activate && cd tf && atlas-init destroy -auto-approve
        if: always()
