name: 'Code Health'

on:
  push:
    branches: "*"
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
        with:
            uv-version: "0.1.12"
      - name: hatch-install
        run: |
          uv pip install -U hatch==1.11.0 zero-3rdparty==0.0.30 --system
      - run: ./py/pre-commit.sh
        name: lint
      - name: build
        run: cd py && hatch build -t wheel --clean-hooks-after
      - name: test
        run: cd py && hatch test --cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: py/.coverage

