name: 'Code Health'

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: "*"
env:
  FORCE_COLOR: "yes"
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
  
  lint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_steps
        uses: "./.github/templates/setup_steps"
      - run: ./py/pre-commit.sh
        name: lint
  type-check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_steps
        uses: "./.github/templates/setup_steps"
      - name: pyright-type-check
        run: cd py && hatch run type:check
  build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_steps
        uses: "./.github/templates/setup_steps"
      - name: build
        run: cd py && hatch build -t wheel --clean-hooks-after
  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_steps
        uses: "./.github/templates/setup_steps"
      - name: test_no_coverage
        run: cd py && hatch test -- -s -vv --tb=short --capture=no --log-cli-level=INFO
      - name: test_with_coverage
        run: cd py && hatch test -- --cov --cov-report=xml -s -vv --tb=short --capture=no --log-cli-level=INFO --ignore=test_atlas_init/test_cli_helper/test_run_manager.py # these tests are somehow stopping the coverage report from being generated
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: py/coverage.xml
  security-check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup_steps
        uses: "./.github/templates/setup_steps"
      - run: cd py && hatch run sec:check
        name: security-check
  workflow-check:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash